In [27]:
import pandas as pd
import numpy as np
df=pd.read_excel('./b站.xlsx')
df.head()

,分区,bv,author,mid,date,url,title,coins,danmu,favorite,likes,replay,share,view
0,科学科普,BV1jb411H7aa,芳斯塔芙,72270557.0,2019-03-14 16:50:49,http://www.bilibili.com/video/av46213558,【鬼谷说】三叶虫：一个平凡家族的不屈与彷徨,102514.0,10851.0,39963.0,99928.0,5536.0,10320.0,1909236.0
1,科学科普,BV1vb411K737,黑白键伯辽兹,135398825.0,2019-04-13 11:09:21,http://www.bilibili.com/video/av49146332,我们的一生，在这部短片前1分钟就结束了,71591.0,38311.0,241565.0,153592.0,13092.0,39198.0,2768916.0
2,科学科普,BV1Ut411p7xq,嘿手视频,383164174.0,2019-01-11 10:08:50,http://www.bilibili.com/video/av40436817,水蛭那么喜欢吸血，吸了502胶水会怎么样？真过瘾！,367.0,1859.0,1774.0,8533.0,1033.0,312.0,2375931.0
3,科学科普,BV1Nb411h7bc,芳斯塔芙,72270557.0,2019-02-27 17:00:53,http://www.bilibili.com/video/av44815270,【鬼谷说】棘皮动物：六亲不认的演化步伐,87330.0,15528.0,47185.0,98254.0,4016.0,25713.0,2846369.0
4,科学科普,BV1Sb411G726,芳斯塔芙,72270557.0,2019-04-19 18:46:49,http://www.bilibili.com/video/av49810786,【鬼谷说】软体动物（其三）：远古王者的不屈征途,93172.0,11946.0,32203.0,88683.0,4950.0,6110.0,1834372.0

In [19]:
df.shape

(50129, 14)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50129 entries, 0 to 50128
Data columns (total 14 columns):
分区          50129 non-null object
bv          50127 non-null object
author      50117 non-null object
mid         50127 non-null float64
date        50126 non-null object
url         50126 non-null object
title       50123 non-null object
coins       50124 non-null float64
danmu       50124 non-null float64
favorite    50124 non-null float64
likes       50124 non-null float64
replay      50124 non-null float64
share       50124 non-null float64
view        50124 non-null float64
dtypes: float64(8), object(6)
memory usage: 5.4+ MB

In [21]:
df_null=df.isnull().sum()
df_null

分区           0
bv           2
author      12
mid          2
date         3
url          3
title        6
coins        5
danmu        5
favorite     5
likes        5
replay       5
share        5
view         5
dtype: int64

In [25]:
df=df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50111 entries, 0 to 50128
Data columns (total 14 columns):
分区          50111 non-null object
bv          50111 non-null object
author      50111 non-null object
mid         50111 non-null float64
date        50111 non-null object
url         50111 non-null object
title       50111 non-null object
coins       50111 non-null float64
danmu       50111 non-null float64
favorite    50111 non-null float64
likes       50111 non-null float64
replay      50111 non-null float64
share       50111 non-null float64
view        50111 non-null float64
dtypes: float64(8), object(6)
memory usage: 5.7+ MB

In [26]:
df=df.drop_duplicates()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48799 entries, 0 to 50128
Data columns (total 14 columns):
分区          48799 non-null object
bv          48799 non-null object
author      48799 non-null object
mid         48799 non-null float64
date        48799 non-null object
url         48799 non-null object
title       48799 non-null object
coins       48799 non-null float64
danmu       48799 non-null float64
favorite    48799 non-null float64
likes       48799 non-null float64
replay      48799 non-null float64
share       48799 non-null float64
view        48799 non-null float64
dtypes: float64(8), object(6)
memory usage: 5.6+ MB

In [29]:
df=df[["分区","author","date","coins","danmu","favorite","likes","replay","share","view"]]
df.head()

,分区,author,date,coins,danmu,favorite,likes,replay,share,view
0,科学科普,芳斯塔芙,2019-03-14 16:50:49,102514.0,10851.0,39963.0,99928.0,5536.0,10320.0,1909236.0
1,科学科普,黑白键伯辽兹,2019-04-13 11:09:21,71591.0,38311.0,241565.0,153592.0,13092.0,39198.0,2768916.0
2,科学科普,嘿手视频,2019-01-11 10:08:50,367.0,1859.0,1774.0,8533.0,1033.0,312.0,2375931.0
3,科学科普,芳斯塔芙,2019-02-27 17:00:53,87330.0,15528.0,47185.0,98254.0,4016.0,25713.0,2846369.0
4,科学科普,芳斯塔芙,2019-04-19 18:46:49,93172.0,11946.0,32203.0,88683.0,4950.0,6110.0,1834372.0

In [31]:
df["分区"].value_counts()

社科人文            15532
汽车               9638
星海               9419
野生技术协会           7060
科学科普             6756
机械               1719
膊Ｕ秸?3532           1
85814               1
锤蠹曳窒恚?50        1
296233              1
563                 1
Name: 分区, dtype: int64

In [32]:
sc=df.loc[df["分区"]=="科学科普"]
so=df.loc[df["分区"]=="社科人文"]
ma=df.loc[df["分区"]=="机械"]
tec=df.loc[df["分区"]=="野生技术协会"]
mi=df.loc[df["分区"]=="星海"]
car=df.loc[df["分区"]=="汽车"]
sc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6756 entries, 0 to 47744
Data columns (total 10 columns):
分区          6756 non-null object
author      6756 non-null object
date        6756 non-null object
coins       6756 non-null float64
danmu       6756 non-null float64
favorite    6756 non-null float64
likes       6756 non-null float64
replay      6756 non-null float64
share       6756 non-null float64
view        6756 non-null float64
dtypes: float64(7), object(3)
memory usage: 580.6+ KB

In [53]:
count=sc.groupby('author')['date'].count().reset_index()
count.columns=['author','times']
com_m=count[count['times']>5]
com_m

               author  times
6              -狐思乱想-      6
11        3Blue1Brown     28
12    404NotFound错误页面     20
21            Alien老吴     15
33            B站好物推荐官      8
46          CodeSheep      6
48             DOG旧档案     49
55              Dva微辣      7
63        FreeBuf官方账号      6
68            H2元素实验室     38
71           Honor大设计      8
83           Linvo说宇宙     68
92       Maxidea极创意官方     19
101           NAKO触手酱     17
109             ONE好奇      7
112      Orchidbear兰熊     11
117           Q-LIMES     18
120     RealChubbyemu     12
134           TIC觅见丛邻      9
150          VIC56_CC      7
152    Veritasium真理元素     10
153      Viktor-Vitya     11
156          Wayne字幕组     53
161            YJango     11
163      YouTube精选字幕组      6
166      Zelo-Balance     31
170          barry看世界     10
184          conandiy     75
189           guertyh      7
192             hey丶o      6
...               ...    ...
935             表象的本质     93
936            袋鼠奇趣科普     10
938               见世屋     20
939             见习搬运工      9
941              观察者网      7
943            观视频工作室     14
944           视光医生马老师     15
950             说来你不信     12
952      谢天宇iiiiiicon      7
954           财联社CC新闻     17
958             资源喵大神      6
961             超人小技巧     14
962           超级健康实验室      7
963              趣味科普      7
972             这知识好冷    138
990              钱丢丢-      6
991               钱雨辰     15
993              银雾影社      9
1008           陈老师敲黑板      6
1010             雪漫车库      6
1016            青知字幕组     24
1018             青鹿中医      6
1019             靓眼科技     10
1032             风竹云墨     10
1035              飞碟说     27
1042        马英俊And马帅气      7
1048         鬼才R才不会数理      6
1051          魔法小分队队长      7
1061             黑毛羊驼     15
1063             龙女之声     86

[223 rows x 2 columns]

In [54]:
last=sc.groupby('author')['date'].max()
late=sc.groupby('author')['date'].min()
F=round((last-late).dt.days/sc.groupby('author')['date'].count()).reset_index()
F.columns=['author','F']
F=pd.merge(com_m,F,on='author',how='inner')
F.describe()

            times           F
count  223.000000  223.000000
mean    22.000000   13.587444
std     28.088021   11.293394
min      6.000000    0.000000
25%      7.500000    5.000000
50%     12.000000   11.000000
75%     20.500000   20.000000
max    173.000000   64.000000

In [55]:
F.loc[F['F'].idxmin()]

author    地球的奇迹
times         6
F             0
Name: 68, dtype: object

In [56]:
F=F.loc[F['F']>0]
F.describe()

            times           F
count  217.000000  217.000000
mean    22.414747   13.963134
std     28.361316   11.216659
min      6.000000    1.000000
25%      8.000000    5.000000
50%     12.000000   11.000000
75%     22.000000   20.000000
max    173.000000   64.000000

In [68]:
danmu=sc.groupby('author')['danmu'].sum()
replay=sc.groupby('author')['replay'].sum()
view=sc.groupby('author')['view'].sum()
count=sc.groupby('author')['date'].count()
I=round((danmu+replay)/view/count*100,2).reset_index()
I.columns=['author','I']
F_I=pd.merge(F,I,on='author',how='inner')
F_I.head()

            author  times     F     I
0           -狐思乱想-      6  29.0  0.22
1      3Blue1Brown     28  15.0  0.03
2  404NotFound错误页面     20  21.0  0.04
3          Alien老吴     15  20.0  0.07
4          B站好物推荐官      8   4.0  0.14

In [70]:
sc['L']=(sc['likes']+sc['coins']*2+sc['favorite']*3)/sc['view']*100
sc.head()

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,分区,author,date,coins,danmu,favorite,likes,replay,share,view,L
0,科学科普,芳斯塔芙,2019-03-14 16:50:49,102514.0,10851.0,39963.0,99928.0,5536.0,10320.0,1909236.0,22.252095
1,科学科普,黑白键伯辽兹,2019-04-13 11:09:21,71591.0,38311.0,241565.0,153592.0,13092.0,39198.0,2768916.0,36.890574
2,科学科普,嘿手视频,2019-01-11 10:08:50,367.0,1859.0,1774.0,8533.0,1033.0,312.0,2375931.0,0.614033
3,科学科普,芳斯塔芙,2019-02-27 17:00:53,87330.0,15528.0,47185.0,98254.0,4016.0,25713.0,2846369.0,14.561324
4,科学科普,芳斯塔芙,2019-04-19 18:46:49,93172.0,11946.0,32203.0,88683.0,4950.0,6110.0,1834372.0,20.259577

In [73]:
L=(sc.groupby('author')['L'].sum()/sc.groupby('author')['date'].count()).reset_index()
L.columns=['author','L']
IFL=pd.merge(F_I,L,on='author')
IFL=IFL[['author','I','F','L']]
IFL.head()

            author     I     F          L
0           -狐思乱想-  0.22  29.0   5.020618
1      3Blue1Brown  0.03  15.0  21.403255
2  404NotFound错误页面  0.04  21.0   3.295228
3          Alien老吴  0.07  20.0  12.520942
4          B站好物推荐官  0.14   4.0   2.022601

In [75]:
IFL.describe()

                I           F           L
count  217.000000  217.000000  217.000000
mean     0.080507   13.963134    9.767456
std      0.074026   11.216659    7.785610
min      0.000000    1.000000    0.748916
25%      0.030000    5.000000    4.390822
50%      0.060000   11.000000    7.311339
75%      0.100000   20.000000   12.707327
max      0.540000   64.000000   38.608865

In [77]:
IFL['I_SCORE']=pd.cut(IFL['I'],bins=[0,0.03,0.06,0.11,1000],labels=[1,2,3,4],right=False).astype(float)
IFL['F_SCORE']=pd.cut(IFL['F'],bins=[0,7,15,30,90,1000],labels=[5,4,3,2,1],right=False).astype(float)
IFL['L_SCORE']=pd.cut(IFL['L'],bins=[0,5.39,9.07,15.58,1000],labels=[1,2,3,4],right=False).astype(float)
IFL.head()

            author     I     F          L  I_SCORE  F_SCORE  L_SCORE
0           -狐思乱想-  0.22  29.0   5.020618      4.0      3.0      1.0
1      3Blue1Brown  0.03  15.0  21.403255      2.0      3.0      4.0
2  404NotFound错误页面  0.04  21.0   3.295228      2.0      3.0      1.0
3          Alien老吴  0.07  20.0  12.520942      3.0      3.0      3.0
4          B站好物推荐官  0.14   4.0   2.022601      4.0      5.0      1.0

In [79]:
IFL['I是否大于平均值']=(IFL['I_SCORE']>IFL['I_SCORE'].mean())*1
IFL['F是否大于平均值']=(IFL['F_SCORE']>IFL['F_SCORE'].mean())*1
IFL['L是否大于平均值']=(IFL['L_SCORE']>IFL['L_SCORE'].mean())*1
IFL.head()

,author,I,F,L,I_SCORE,F_SCORE,L_SCORE,I是否大于平均值,F是否大于平均值,L是否大于平均值
0,-狐思乱想-,0.22,29.0,5.020618,4.0,3.0,1.0,1,0,0
1,3Blue1Brown,0.03,15.0,21.403255,2.0,3.0,4.0,0,0,1
2,404NotFound错误页面,0.04,21.0,3.295228,2.0,3.0,1.0,0,0,0
3,Alien老吴,0.07,20.0,12.520942,3.0,3.0,3.0,1,0,1
4,B站好物推荐官,0.14,4.0,2.022601,4.0,5.0,1.0,1,1,0

In [80]:
IFL['人群数值']=(IFL['I是否大于平均值']*100)+(IFL['F是否大于平均值']*10)+(IFL['L是否大于平均值']*1)
IFL.head()

,author,I,F,L,I_SCORE,F_SCORE,L_SCORE,I是否大于平均值,F是否大于平均值,L是否大于平均值,人群数值
0,-狐思乱想-,0.22,29.0,5.020618,4.0,3.0,1.0,1,0,0,100
1,3Blue1Brown,0.03,15.0,21.403255,2.0,3.0,4.0,0,0,1,1
2,404NotFound错误页面,0.04,21.0,3.295228,2.0,3.0,1.0,0,0,0,0
3,Alien老吴,0.07,20.0,12.520942,3.0,3.0,3.0,1,0,1,101
4,B站好物推荐官,0.14,4.0,2.022601,4.0,5.0,1.0,1,1,0,110

In [84]:
def tranform_label(x):
    if x==111:
        label='好价值up主'
    elif x==101:
        label='高价值托更up主'
    elif x==11:
        label='高质量内容高深up主'
    elif x==1:
        label='高质量内容高深托更up主'
    elif x==110:
        label="接地气活跃up主"
    elif x==10:
        label='活跃up主'
    elif x==100:
        label='接地气up主'
    elif x==0:
        label='还在成长up主'
    return label

In [86]:
IFL['人群类型']=IFL['人群数值'].apply(tranform_label)
IFL.head()

,author,I,F,L,I_SCORE,F_SCORE,L_SCORE,I是否大于平均值,F是否大于平均值,L是否大于平均值,人群数值,人群类型
0,-狐思乱想-,0.22,29.0,5.020618,4.0,3.0,1.0,1,0,0,100,接地气up主
1,3Blue1Brown,0.03,15.0,21.403255,2.0,3.0,4.0,0,0,1,1,高质量内容高深托更up主
2,404NotFound错误页面,0.04,21.0,3.295228,2.0,3.0,1.0,0,0,0,0,还在成长up主
3,Alien老吴,0.07,20.0,12.520942,3.0,3.0,3.0,1,0,1,101,高价值托更up主
4,B站好物推荐官,0.14,4.0,2.022601,4.0,5.0,1.0,1,1,0,110,接地气活跃up主

In [88]:
cat=IFL['人群类型'].value_counts().reset_index()
cat['人数占比']=cat['人群类型']/cat['人群类型'].sum()
cat

          index  人群类型      人数占比
0         活跃up主    46  0.211982
1      高价值托更up主    34  0.156682
2      接地气活跃up主    34  0.156682
3    高质量内容高深up主    28  0.129032
4        好价值up主    25  0.115207
5        接地气up主    23  0.105991
6       还在成长up主    20  0.092166
7  高质量内容高深托更up主     7  0.032258

In [97]:
import matplotlib.pyplot as plt
plt.figure(figsize=(15,5))
plt.pie(cat['人数占比'],labels=cat[1],autopct='%1.2f%%')
plt.show()

KeyError: 1